# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='favorCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='opposeCount',
            field=models.IntegerField(default=0),
        ),
    ]
