# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-25 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20240311_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='owner',
            new_name='toBlog',
        ),
    ]
