# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-11 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20240325_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-ctime',)},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='surfix',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='theme',
            field=models.IntegerField(choices=[(0, 'homeBlue'), (1, 'homeRed')]),
        ),
    ]
