# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-21 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20240411_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesdetail',
            name='content',
            field=models.TextField(),
        ),
    ]
