# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20240621_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='troubleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='troubles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=256)),
                ('ctime', models.DateTimeField()),
                ('mark', models.IntegerField(blank=True, choices=[(0, 'bad'), (1, 'common'), (2, 'good')], null=True)),
                ('status', models.IntegerField(choices=[(0, 'Have not processed'), (1, 'Processing'), (2, 'Processed')], default=0)),
                ('solution', models.TextField()),
                ('ptime', models.DateTimeField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.troubleDetail')),
                ('thePoser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poser', to='repository.users')),
                ('theProcesser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processer', to='repository.users')),
            ],
        ),
    ]
