# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-25 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_troubledetail_troubles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubles',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
