# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20240628_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='solutionAlternated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
    ]
